feat: Refactor CMake project
spglib/spglib pull request #397
Opened 2024-01-19 21:47 UTC by LecrisUT

Main things here:
- Refactored apis and tests to be standalone sub-projects. This allows the subprojects to be built and run separately from pre-installed Spglib library
- Run all tests within ctest (packaging and examples)
- Have Fedora re-run all tests after installing the project

Depends on #362 (maybe also #271)
Closes #363

2024-01-19 21:49 UTC, LecrisUT commented
Would be nice to have this one ready for the CECAM meeting so I can use it as an example project

2024-01-19 23:54 UTC, LecrisUT commented on test/CMakeLists.txt
> +				-fsanitize=${SPGLIB_USE_SANITIZER} -static-libasan
Note to self: use shared-library sanitizer, but add `LD_PRELOAD` to `find_library(libasan)`: https://github.com/Kitware/VTK/blob/b541e465508aab1f6ad4c863e71d0a422301dda2/CMake/vtkSanitize.cmake#L29

2024-01-25 19:56 UTC, LecrisUT commented on test/CMakeLists.txt
> +add_subdirectory(example)
TODO: bump the example's minimum CMake

2024-01-29 10:01 UTC, lan496 commented
Can you write a document for directory structure under `test/` in `test/README.md`?

2024-01-29 10:06 UTC, lan496 commented
Can you explain what *.fmf are used for?

2024-01-29 10:06 UTC, lan496 requested changes

2024-01-29 10:06 UTC, lan496 commented on example/c_api
> +../test/example/c_api/
Does this link work in GitHub?

2024-01-29 10:06 UTC, lan496 commented on CMakeLists.txt
> +		set(Spglib_IS_TOP_LEVEL ON)
Is `Spglib_IS_TOP_LEVEL` documented in some READMD?

2024-01-29 10:06 UTC, lan496 commented on test/example/c_api/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20)
Newer cmake required?

2024-01-29 10:11 UTC, LecrisUT commented on CMakeLists.txt
> +		set(Spglib_IS_TOP_LEVEL ON)
This one is auto-generated: https://cmake.org/cmake/help/latest/command/project.html#synopsis
And it is a local variable (i.e. it is always overwritten, as opposed to cache/env variables), so the user has no way of editing it.

2024-01-29 10:18 UTC, LecrisUT commented on test/example/c_api/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20)
For the examples, just to make life easier with the `Spglib_ROOT` vs `Spglib_DIR`. Also to discourage the users to rely on the antiquated cmake versions that we do not test (should also add a matrix of cmake versions to the CI). It is hard to test the examples on lower CMake version because we would have to do it outside the test-suite

2024-01-29 10:21 UTC, LecrisUT commented on example/c_api
> +../test/example/c_api/
On Github it just shows symlink, but when you git clone, it should just create the appropriate symlink. I don't have access to a windows machine to test it there as well.

2024-01-29 17:50 UTC, LecrisUT commented
> Can you explain what *.fmf are used for?

I will write a more detailed explanation in the test readme file, but in a nutshell, it defines the tests in testing-farm, and you can interact with them using [`tmt`](https://github.com/teemtee/tmt) (or [`fmf`](https://github.com/teemtee/fmf) to read the `fmf` files like `yaml` files). In principle you can execute those codes locally, but because this has dependencies, it can only be done in/with a Fedora-like OS/container/VM [^1]

[^1]: https://github.com/teemtee/tmt/pull/2557

2024-01-29 23:13 UTC, lan496 commented on CMakeLists.txt
> +		set(Spglib_IS_TOP_LEVEL ON)
I see. Thanks!

2024-01-30 21:43 UTC, LecrisUT commented on CMakeLists.txt
>  endif ()
Simplify these by setting `cmake_minimum_required (min...max)`. It haa tge same effect as `cmake_policy(SET NEW)`

2024-02-08 14:45 UTC, LecrisUT commented
@lan496  Ok, I've finally managed to write more details about the test-suite. We should start linking these to the main sphinx documentation and migrate the python and fortran documents as well.

2024-02-08 14:47 UTC, LecrisUT commented on test/README.md
> +#### VSCode setting
We should move these to `develop.md` or similar instead.

2024-02-09 23:54 UTC, lan496 approved these changes
LGTM. `test/README.md` looks good for overview.

BTW, You mark this PR as a draft. Do you have remained things? If no, please merge this PR.

2024-02-10 06:23 UTC, LecrisUT commented
> BTW, You mark this PR as a draft.

I have marked all non v2.3.1 PRs as draft to prevent them from being merged before those. Otherwise I only have to write a few notes in the changelog.md. #335 and #308 are done as well, particularly try out #308 and let me know if editable works for documentation and everything

2024-02-13 01:06 UTC, lan496 commented
testing-farm:fedora-39-aarch64 seems to be failed.
https://github.com/spglib/spglib/pull/397/checks?check_run_id=21471792985

2024-02-13 04:40 UTC, LecrisUT commented
Thnx, didn't notice it. It seemed it was just a network issue. I have just restarted it.

2024-02-13 06:21 UTC, lan496 approved these changes

2024-02-13 06:23 UTC, merged